### ISSUE TITLE
stamina bar get stuck

### ISSUE THREAD

**Issue by HamedAlmanthari** [ButteryStancakes/AccurateStaminaDisplay#2]
the title is self explanatory. i'm not sure if another mod is conflicting with this mod or v49 just broke it. sometimes it works, sometimes the bar get stuck halfway through or full. i'm not using any other hud mod.

**Comment by ButteryStancakes** [comment]
According to some helpful folks in the Discord thread, this seems to be an issue correlating to [PushCompany](https://github.com/Cedeli/PushCompany), specifically the stamina cost for pushing other players.

As of right now, I'm not sure if this is something that can be fixed on my end, but I will take a look at it.

It sounds like a temporary workaround is to just disable the stamina cost entirely in PushCompany's config - others have reported this resolving the conflict.

**Comment by HamedAlmanthari** [comment]
thanks for the reply! i already knew about this and i stopped using PushCompany for this reason.
