### ISSUE TITLE
[Bug] Change color setting not working with MoreCompany

### ISSUE THREAD

**Issue by ytitnE** [ButteryStancakes/AccurateStaminaDisplay#5]
If you have MoreCompany, the color won't change color after the first bar of the stamina. Which I find very weird how it effects it, because when you're in the last bar it will change color to red, but anything after that it will not. I just had these two mods in a profile and it was doing it, very easy to replicate. If you need me to provide a video I can. Love the mod, appreciate the work

Edit: It's more like the second line that goes through the stamina bar and a little after it, anything after that it won't change color

**Comment by ButteryStancakes** [comment]
I've fixed this in 2.1.4. Apologies for the delay but I didn't notice the issue until someone posted it in the Discord thread.

No idea when this broke... the problem was with some code I refactored forever ago, so it must have been around for quite a while. Sorry for the inconvenience!!
